default:
  github_token: "your_github_token_here"
  api_key: "your_api_key_here"
  update_interval: 86400
  email:
    smtp_server: "smtp.qq.com"
    smtp_port: 465
    from: "your_email@qq.com"
    password: "your_email_password" # QQ邮箱需要使用授权码
    to: "receiver@example.com"
  notification_settings:
    enabled: true
    frequency: "daily"
  subscriptions_file: "subscriptions.json"
